// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require("request");

  module.exports = function(execServer) {
    return function(req, res) {
      return request.post({
        uri: "http://" + execServer + "/exec",
        json: true,
        form: {
          code: req.body.code
        }
      }, function(error, response, body) {
        return res.send(body);
      });
    };
  };

}).call(this);
